dist: trusty
sudo: require
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - libboost-dev
      - libboost-system-dev
      - libboost-program-options-dev
      - libboost-all-dev
      - libyaml-cpp-dev
branches:
  only:
    - master
script:
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - gcc -v && g++ -v && cmake --version
  - cd .. && export WORK_ROOT_DIR="$(pwd)"
  - git clone 'https://github.com/jbeder/yaml-cpp.git' "${WORK_ROOT_DIR}/yaml-cpp" && cd "${WORK_ROOT_DIR}/yaml-cpp" && git checkout 'yaml-cpp-0.6.2'
  - mkdir -p "${WORK_ROOT_DIR}/yaml-cpp-build" && cd "${WORK_ROOT_DIR}/yaml-cpp-build"
  - cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Release "${WORK_ROOT_DIR}/yaml-cpp"
  - chrt --batch 0 make -l$(nproc) -j$(nproc) install
  - mkdir -p "${WORK_ROOT_DIR}/build" && cd "${WORK_ROOT_DIR}/build"
  - cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Release "${WORK_ROOT_DIR}/ufw"
  - chrt --batch 0 make -l$(nproc) -j$(nproc) all
  - chrt --batch 0 make BOOST_TEST_LOG_LEVEL=all unit-test
  
